# Setup
title:        Raúl Martínez
tagline:      WordPress developer
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Raúl Martínez

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown